version: "3.3"
services:
  app:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory.
      context: ./app
    environment:
      # Variables to connect to our Postgres server.
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: app_dev
      PGPORT: 5432
      # Hostname of our Postgres container.
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - '4001:4001'
    depends_on:
      # The DB container needs to be started before we start this container.
      - db
  db:
    # We use the predefined Postgres image.
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
       # Set user/password for Postgres.
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
